# See https://nexte.st/book/configuration#profiles
[profile.default]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false

# See https://nexte.st/book/junit
[profile.default.junit]
# a JUnit report will be written out to spec/rust/target/nextest/default/junit.xml
path = "junit.xml"
